import Head from "next/head";
import Image from "next/image";
import { Inter } from '@next/font/google';
const inter = Inter({ subsets: ['latin'] });

// const myFont = localFont({ src: '../public/assets/fonts/newyork.otf' });

export default function Home() {
  return (
    <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="h-full flex p-24 text-white flex-col text-3xl align-middle text-center">
            <div className="flex flex-row-reverse">
                <a
                    className="flex align-middle text-center"
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                <p className="text-base">By</p>
                
                <Image
                    src="/vercel.svg"
                    alt="Vercel Logo"
                    className="invert"
                    width={100}
                    height={24}
                    priority
                />
                </a>
            </div>
            <div className="font-NewYork p-32">
                Chen's personal website
            </div>
            <div className="grid grid-cols-2">
                <a href="/plans" className="group h-20">
                    <h2 className={inter.className}>
                        <span className="font-semibold">
                            Plans
                        </span>
                        <span
                            className="inline-block group-hover:translate-x-2 ease-in-out transition duration-100"
                        >
                            -&gt;
                        </span>
                    </h2>
                </a>
                <a href="/articles" className="group h-20">
                    <h2 className={inter.className}>
                        <span className="font-semibold">
                            Articles
                        </span>
                        <span
                            className="inline-block group-hover:translate-x-2 transition duration-100"
                        >
                            -&gt;
                        </span>
                    </h2>
                </a>
                <a href=""></a>
                <a href=""></a>
            </div>
        </main>
    </>
  );
}
